### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by Owen3H** [Dreadrith/LC_EasySync#1]
Heyo, thought I'd let you know the repo should probably have a README instead of a big wall of lawyer speak :P
Great stuff btw, this is essentially what I wanted to achieve with `SyncedConfig` but yet to do extensive testing with.

**Comment by Dreadrith** [comment]
Thank you! I wanted to show it to you before release but I couldn't contact you through Discord directly lol.
Not sure what you mean by wall of lawyer speak but I hadn't added a README cause I dislike documenting :)
Maybe I'll copy the one from the thunderstore listing.

**Comment by Owen3H** [comment]
I feel you, it can be more time consuming than making the library xd
You're welcome to DM me, I just don't want to be in that cesspit of a server.

**Comment by Dreadrith** [comment]
Added a README https://github.com/Dreadrith/LC_EasySync/commit/8fbf1543b6501cc0c21399bb6e6a6123dbd137a3
